In [1]:
import pandas as pd
import glob
import pandas as pd
from datetime import datetime
pd.set_option('display.max_colwidth', None)

In [2]:
li = [] # add dataframes to this list
df = pd.DataFrame()
path = "local-data"

# all_files = glob.glob(path + "/*", recursive=True)
all_files = glob.glob(path + '**/**/*.xlsx', recursive=True)
for filename in all_files:
    
    print(filename)
    
#     tmp = pd.read_csv(filename, 
#                   dtype=str,
#                   encoding = "ISO-8859-1"
#                        )
    tmp = pd.read_excel(filename, 
              dtype=str,
              header=0)
    
    # approach 1 if columns not always identical
    if len(df)==0:
        df = tmp.copy()
    else:
        df = pd.concat([df, tmp], axis=0, ignore_index=True)
        print(df.shape)
    
        
    # approach 2 if columns always identical
#     li.append(tmp) 
    del tmp
print('Done')

local-data/2019/2019_01/Incidents 01_2019.xlsx
local-data/2019/2019_01/Service Request 01_2019.xlsx
(51425, 45)
local-data/2019/2019_02/Incidents 02_2019.xlsx
(73713, 45)
local-data/2019/2019_02/Service Request 02_2019.xlsx
(100188, 45)
local-data/2019/2019_03/Incidents 03_2019.xlsx
(125727, 45)
local-data/2019/2019_03/Service Request 03_2019.xlsx
(152746, 45)
local-data/2019/2019_04/Incidents 04_2019.xlsx
(177707, 46)
local-data/2019/2019_04/Service Request 04_2019.xlsx
(205981, 46)
local-data/2019/2019_05/Incidents 05_2019.xlsx
(231779, 47)
local-data/2019/2019_05/Service Request 05_2019.xlsx
(261816, 47)
local-data/2019/2019_06/Incidents 06_2019.xlsx
(286145, 47)
local-data/2019/2019_06/Service Request 06_2019.xlsx
(313022, 47)
local-data/2019/2019_07/Incidents 07_2019.xlsx
(342563, 48)
local-data/2019/2019_07/Service Request 07_2019.xlsx
(374102, 48)
local-data/2019/2019_08/Incidents 08_2019.xlsx
(399356, 48)
local-data/2019/2019_08/Service Request 08_2019.xlsx
(425991, 48)
local-data/2019/2019_09/Incidents 09_2019.xlsx
(451689, 48)
local-data/2019/2019_09/Service Request 09_2019.xlsx
(477083, 48)
local-data/2019/2019_10/Incidents 10_2019.xlsx
(501049, 48)
local-data/2019/2019_10/Service Request 10_2019.xlsx
(530066, 48)
local-data/2019/2019_11/Incidents 11_2019.xlsx
(551678, 48)
local-data/2019/2019_11/Service Request 11_2019.xlsx
(578262, 48)
local-data/2019/2019_12/Incidents 12_2019.xlsx
(596403, 48)
local-data/2019/2019_12/Service Request 12_2019.xlsx
(617700, 48)
local-data/2020/Incidents 01_2020.xlsx
(639402, 48)
local-data/2020/Incidents 02_2020.xlsx
(662356, 48)
local-data/2020/Incidents 03_2020.xlsx
(687927, 49)
local-data/2020/Incidents 04_2020.xlsx
(709002, 49)
local-data/2020/Incidents 05_2020.xlsx
(729215, 49)
local-data/2020/Incidents 06_2020.xlsx
(752243, 49)
local-data/2020/Incidents 07_2020.xlsx
(776644, 49)
local-data/2020/Incidents 08_2020.xlsx
(798705, 51)
local-data/2020/Incidents 09_2020.xlsx
(821362, 51)
local-data/2020/Incidents 10_2020.xlsx
(845220, 51)
local-data/2020/Incidents 11_2020.xlsx
(868245, 51)
local-data/2020/Incidents 12_2020.xlsx
(888076, 51)
local-data/2020/Service Request 01_2020.xlsx
(916163, 51)
local-data/2020/Service Request 02_2020.xlsx
(942154, 51)
local-data/2020/Service Request 03_2020.xlsx
(970506, 51)
local-data/2020/Service Request 04_2020.xlsx
(990677, 51)
local-data/2020/Service Request 05_2020.xlsx
(1010385, 51)
local-data/2020/Service Request 06_2020.xlsx
(1033503, 51)
local-data/2020/Service Request 07_2020.xlsx
(1058090, 51)
local-data/2020/Service Request 08_2020.xlsx
(1081062, 51)
local-data/2020/Service Request 09_2020.xlsx
(1105105, 51)
local-data/2020/Service Request 10_2020.xlsx
(1128057, 51)
local-data/2020/Service Request 11_2020.xlsx
(1148108, 51)
local-data/2020/Service Request 12_2020.xlsx
(1166704, 51)
Done

In [ ]:
# use for appraoch 2
# make a dataframe of all the files combined
# df = pd.concat(li, axis=0, ignore_index=True)
# print(df.shape)
# df.head(1)
# print(df.columns)

In [10]:
sorted(df.columns)
# df = df.iloc[:,:-2]
# df.shape
# df.sample(5)

['Affected Customer Contract Type',
 'BAT - 5TC - Component',
 'BAT - 5TC - Primary Cause',
 'BAT - 5TC - Service',
 'BAT - 5TC - Service Group',
 'BAT - 5TC - Sub-Component',
 'BAT - OLA Name for Team',
 'BAT - OLA Resolve By Deadline',
 'Call Source',
 'Category',
 'Cause',
 'Close Description',
 'Closed By',
 'Closed Date Time',
 'Closed on 1st Call',
 'Country',
 'Created By',
 'Created Date Time',
 'Customer Display Name',
 'Customer Email',
 'Customer Language',
 'Customer Site Name',
 'Default Team',
 'Description',
 'Description.1',
 'First Agent Contact',
 'GDC',
 'Incident ID',
 'Incident Type',
 'IncidentDurationInHours',
 'Is Fujitsu Owned',
 'Last Modified By',
 'Last Modified Date Time',
 'OneID',
 'Owned By',
 'Owned By Team',
 'Primary Affected Site',
 'Priority',
 'Region',
 'SLA Name',
 'Service',
 'Short Description',
 'Site Hours SLA Resolution Deadline',
 'Status',
 'Subcategory',
 'Supported',
 'VIP',
 'stat_Date Last Approval Action',
 'stat_Date Time Assigned',
 'stat_Date Time Resolved',
 'stat_ValidMonthForFCIFCR']

In [11]:
df[].head(1)

,SLA Name,Incident Type,Cause,OneID,Country,Incident ID,Customer Site Name,Customer Display Name,Status,Priority,...,Last Modified By,BAT - 5TC - Service Group,BAT - 5TC - Service,BAT - 5TC - Component,BAT - 5TC - Sub-Component,BAT - 5TC - Primary Cause,GDC,stat_Date Time Assigned,Customer Email,Region
0,Platinum,Incident,Data - Master Data,85059926,Mexico,CH4338995,NaN,Cristian Eduardo Cavazos Torres,Closed,4,...,Cherwell Services,NaN,NaN,NaN,NaN,NaN,BAT COS01 GDC,NaN,NaN,NaN

In [5]:
# df[df['Incident Number']=='271063']

In [3]:
df.to_csv("local-data/bat_2019_2020_combined.csv", index=False)
# del df